### ISSUE TITLE
icon too big

### ISSUE THREAD

**Issue by seujungkuku** [newhoa/victory-gtk-theme#10]
I'm using victory-gtk-theme and victory-icon-theme, this bug on theme or icon? 

right click on nemo file manager 3.4.7

![victory-gtk-theme](https://lh3.googleusercontent.com/Tcj_jdLkcTDyd8bxmISfDxl3yW3xI3i_zSmOr92w3nMt9v9ghd4ajxSE4eJGdsD--1Cc76xnu0MjgRzIQz_8oetY2qT16bpcJY0yzeQrz-Mn4HmCw3irzZlpWKAnxdfqWD4BBiSViyZnFnk8pXg22b8mpSzBH6quYhWmO-doMqSvdZJWXDrRABWUHf7UmOjG3az2_bZDg_GXVoZ2T6_2gp5t6YbOq3H968ugs1sEjWQ2zdG-xcI0HtYZY3e8_gO2IRusC7OSBJ-8kgnfL4X2JO1yEWzk7TRaJATp04pcecN1nb12xOWy_F9I_gKjfZ_J2KLXHBVdyF9jwzqt73Kt2wp91eMhfIpRQFjXvIt69Pe9KlbX50fRcpULIoLmljPCL2-mdhUS9N3hU9FJ6Trr5npjpfYz8HALR9Vi0DGNqzjYZHII0wilhoe4kby09QXjMeyp1YfwtqQhi4JsCMagKCQrvDojBqddUJEvPOTifV2Fg9UImHL9p9qyvdCJKJvJGZJl3QKGIeF-w7bn24pF1OGKEvY8LTG7T6Rmx0PYLTFKz88pNoJVVc2bFcBkNT30xANW5cgAPjfLUY3OPBhe-Qly3Y7GuqVeZLmMA4Tv96d-WN6RQo2QAYq6BsWvJ9y3UlQX1xnZ8wmkehIRNo0W3bRPFxvzTD0XZfA=w309-h281-no)

__
mint xfce 18.2 sonya 32bit

**Comment by newhoa** [comment]
Hi, thanks for the screenshot. This is an icon theme bug and should be fixed in the latest version of the icon theme ([since this Oct 18 fix](https://github.com/newhoa/victory-icon-theme/issues/9)). Delete the icon theme redownload it, and log out and back in and see if it still happens. If so comment in the linked bug thread on the icon theme repo. Thanks!
